version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: marked
    versions:
    - 1.2.8
    - 1.2.9
    - 2.0.1
  - dependency-name: markdown-it-anchor
    versions:
    - 7.0.0
    - 7.0.2
  - dependency-name: semver
    versions:
    - 7.3.4
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: handlebars
    versions:
    - 4.7.6
